version: "3.8"
services:
    app:
        image: node:12-alpine
        command: sh -c "npm install && npm i pm2 -g && pm2-runtime start app.js"
        ports:
            - 1337:1337
        working_dir: /app
        volumes: 
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: sails
            NODE_ENV: production
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: sails
volumes:
    mysql-data: